import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>techawks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <h1 className='text-green-500'>Lets get it</h1>
    </div>
  )
}
