import Head from 'next/head'


export default function Home() {
  return (
    <div>
      <Head>
        <title>techawks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Welcome to the home page we are under construction please navigate to the products :)</h1>
    </div>
  )
}
